default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ramminti_development

test:
  <<: *default
  database: ramminti_test

production:
  <<: *default
  database: ramminti_production
  username: ramminti
  password: <%= ENV["RAMMINTI_DATABASE_PASSWORD"] %>
